config/routes.rb
require 'sidekiq/web'

Dating::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get 'signup' => 'users#new'
  get 'terms' => 'users#terms_of_use'
  get 'faq' => 'users#faq'
  get 'privacy' => 'users#privacy_policy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  get "/profile/:id" => "users#show"
  get "profile/:id/settings" => 'users#edit'
  get 'settings/:id' => 'users#settings'
  get 'admin/users' => 'admin#users'
  get 'admin/subscriptions' => 'admin#subscriptions'
  get 'admin/letsgo' => 'admin#letsgo'
  get 'admin/messages' => 'admin#messages'
  get 'admin/qanda' => 'admin#qanda'
  get 'admin/pictures' => 'admin#pictures'
  get 'letsgos/eatdrink' => 'letsgos#eatdrink'
  get 'letsgos/listenwatch' => 'letsgos#listenwatch'
  get 'letsgos/play' => 'letsgos#play'
  get 'letsgos/other' => 'letsgos#other'
  get 'letsgos/explore' => 'letsgos#explore'
  get "subscriptions/cancelsubscription"
  get "subscriptions/updatesubscription"
  get "subscriptions/changecard"
  get "subscriptions/suspend"
  get "subscriptions/updatebilling"
  get "subscriptions/reactivate"
  get ":id/updatebilling" => "users#update_stripe_billing"
  match '/edit_card',   to: 'subscriptions#edit_card',   via: 'get'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  get '/relationships/set_follow' => 'relationships#set_follow'
  get '/users/set_follow' => 'users#set_follow'
  get '/speed_dates' => 'users#speed_date'
  get '/disconnect_facebook' => 'users#disconnect_facebook'
  get '/disconnect_twitter' => 'users#disconnect_twitter'

  post 'subscription_event' => "webhooks#subscription_event"
  

    
    resources :messages do
      member do
      post :askout
      end
    end

  resource :twitter do
    get :authorize
    get :return
  end

  get '/auth/facebook', as: "auth_provider"
  get '/auth/facebook/callback', to: 'facebooks#callback'

  match '/paypal/ipn' => 'notifications#create', :via => [:get, :post], :as => 'notifications_create'
  
  resources :admin
  resources :charges
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'paypal/subscription', to: 'subscriptions#paypal_subscription_record', :as => 'paypal_subscription_create'
 
  resources :sessions
  resources :contacts, only: [:new, :create]
  resources :password_resets
  resources :galleries
  resources :photos do
    member do
      post :avatar
    end
  end
  resources :searches do
	get 'save_searches', on: :collection
	get 'load_search', on: :collection
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :letsgos, only: [:create, :destroy]
  resources :users do  
    get 'settings', on: :member  
    post 'follow', on: :member 
    post 'unfollow', on: :member
    get "follow", on: :member 
    get 'follow_popup', on: :member
    post :search, on: :collection
  end
  
  resources :letsgos do
    member do
      post :repost
      post :interested
    end
  end
  
  resources :questions do
    resources :answers, only: [:new, :create]
  end

          
  root to: 'users#index'
  
  resources :users do
  end
 
 resources :conversations do
     post :reply, on: :member
     post :trash_all, on: :collection
     post :untrash, on: :collection
   end

  resources :payments, only: [:show, :create, :destroy] do
     collection do
       get :success
       get :cancel
       post :notify
     end     
   end
   

end

app/views/admin/index.html.erb
Admin Panel
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Question & Answers", admin_qanda_path %> | <%= link_to "Pictures", admin_pictures_path %>  

app/views/admin/letsgo.html.erb
Lets Go Statistics
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Question & Answers", admin_qanda_path %> | <%= link_to "Pictures", admin_pictures_path %>  
<p>
	
		<div class="row">
		  <div class="col-xs-6">
		    <b>Dates Per Day<b>
		    <%= line_chart Letsgo.group_by_day(:created_at).count %>
			<b>Dates Per Month<b>
		    <%= line_chart Letsgo.group_by_month(:created_at).count %>
		  </div>

		</div>
		<P>
		<P>
		<%= Letsgo.count %> total Dates
		<p>
		<%= Letsgo.total_male %> Dates by Males
		<P>
		<%= Letsgo.total_female %> Dates by Females 
								<P>
			TAG: <%= link_to "Eat/Drink", letsgos_eatdrink_path %> | <%= link_to "Listen/Watch", letsgos_listenwatch_path %> | <%= link_to "Play", letsgos_play_path %> | <%= link_to "Explore", letsgos_explore_path %> | <%= link_to "Other", letsgos_other_path %>   

			<% for letsgo in @letsgos %>

			  <li>
			    <b>Let's Go...<span class="content"><%= letsgo.content %></span></b> posted by: <%= link_to letsgo.user.username, letsgo.user %>
			       <%= link_to 'Delete', { :controller => 'letsgos', :action => 'destroy', :id => letsgo.id }, 
				                      { :confirm => 'Are you sure?', :method => :delete} %>
			     
			  <% end %>

			</li>			

app/views/admin/messages.html.erb
Messages Statistics
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Question & Answers", admin_qanda_path %> | <%= link_to "Pictures", admin_pictures_path %>     
<p>
	
		<div class="row">
		  <div class="col-xs-6">
		    <b>Messages By Day<b>
		    <%= line_chart Notification.group_by_day(:created_at).count %>
			<b>Messages By Month<b>
		    <%= line_chart Notification.group_by_month(:created_at).count %>
		  </div>

		</div>
		<P>
		<P>
		<%= Notification.count %> total Messages
		<p>
			<%= Notification.count %> total Messages
<p>
	<%= User.total_male_messages %> Total Male Messages
	<p>
		<%= User.total_female_messages %> Total Female Messages
		

app/views/admin/pictures.html.erb
Pictures Statistics
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Question & Answers", admin_qanda_path %>
<p>
	
	<div class="row">
	  <div class="col-xs-6">
	    <b>Photos Per Day<b>
	    <%= line_chart Photo.group_by_day(:created_at).count %>
		<b>Photos Per Month<b>
	    <%= line_chart Photo.group_by_month(:created_at).count %>
	  </div>

	</div>
	<p>
	<P>
	<%= Photo.count %> total Photos
	<P>
		<p>
		<%= Photo.total_male %> Male photos
		<P>
		<%= Photo.total_female %> Female photos
		<p>
	<% @photos.sort_by(&:created_at).reverse.each do |photo| %>
	<%= link_to photo.user.username, photo.user %>
	<p>
	   <%=image_tag photo.image_url(:thumb) %>
	<P>
		<%= photo.created_at.strftime("%B %e, %Y") %>
		
		<P>
	<%= button_to "remove", photo, :confirm => 'Are you sure?', :method => :delete %>
	<% end %>

app/views/admin/qanda.html.erb
Question & Answers Statistics
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Pictures", admin_pictures_path %>  
<p>
	
		<div class="row">
		  <div class="col-xs-6">
		    <b>Questions By Day<b>
		    <%= line_chart Question.group_by_day(:created_at).count %>
			<b>Questions By Month<b>
		    <%= line_chart Question.group_by_month(:created_at).count %>
		  </div>

		</div>
		<P>
		<%= Question.count %> total questions
		<P>
		<%= Question.total_answer %> total answers
		<P>
		<%= Question.total_answer_cancelled %> Unanswered Questions
		<P>
		<%= Question.total_male %> Questions from guys
			<P>
		<%= Question.total_female %> Questions from females
			<P>
		
		  <% @questions.each do |question| %>
		    <li><%= question.question %>  </li><%= button_to "remove", question, :confirm => 'Are you sure?', :method => :delete %>
		<%= question.answer %>
		  <% end %>

app/views/admin/subscriptions.html.erb
Subscription Statistics
<p>
<%= link_to "Users", admin_users_path %> | <%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Question & Answers", admin_qanda_path %> | <%= link_to "Pictures", admin_pictures_path %>  
<p>
	
	<div class="row">
	  <div class="col-xs-6">
	    <b>Subscriptions By Day<b>
	    <%= line_chart Subscription.group_by_day(:created_at).count %>
		<b>Subscriptions By Month<b>
	    <%= line_chart Subscription.group_by_month(:created_at).count %>
	  </div>

	</div>
	<p>
	<%= Subscription.total_active %> active subscribers
	<P>
	<%= Subscription.count %> total subscribers
	<P>
	<%= Subscription.total_cancelled %> Cancelled subscribers
	<P>
	<%= Subscription.total_paypal_recurring_profile_token %> PayPal subscribers
	<P>
			<%= Subscription.total_active_paypal %> Active PayPal subscribers
			<P>
		
	<%= Subscription.total_stripe_customer_token %> Stripe subscribers
	<P>
		<%= Subscription.total_active_stripe %> Active Stripe subscribers
		<P>

	<%= Subscription.total_stripe_cancelled %> Stripe cancelled subscribers
	<P>
	<%= Subscription.total_paypal_cancelled %> Paypal cancelled subscribers
	<P>
	<%= Subscription.total_annual %> Annual Subscribers
	<P>
	<%= Subscription.total_monthly %> Monthly Subscribers
	<P>
	<%= Subscription.total_male %> Male Subscribers
	<P>
	<%= Subscription.total_female %> Female Subscribers
	


		<table class="pretty">
		  <tr>
		    <th>ID</th>
		    <th>User</th>
		    <th>Length</th>
		    <th>Date</th>
		    <th>Type</th>
		    <th>Cancelled</th>
		
		
		  </tr>
		  <% @users.sort_by {|user| user.subscription.created_at}.reverse.each do |user| %>
		    <tr>
		      <td><%= user.subscription.id %></td>
		      <td><%= link_to user.username, user %></td>
		      <td><%= user.subscription.plan.name %></td>
		      <td><%= user.subscription.created_at.strftime("%B %e, %Y") %></td>
		      <td><% if user.subscription.stripe_customer_token.nil? %> PAYPAL <% end %>
		<% if user.subscription.paypal_recurring_profile_token.nil? %> STRIPE  
			<% end %></td>
			<td><% if user.subscription.cancelled.nil? %> No <% end %>
				<% if user.subscription.cancelled %> Yes  
					<% end %></td>
		
		    </tr>
		  <% end %>
		</table>
		<%= will_paginate(@users) %>

app/views/admin/users.html.erb
User Statistics
<p>
<%= link_to "Subscriptions", admin_subscriptions_path %> | <%= link_to "Messages", admin_messages_path %> | <%= link_to "Lets Go's Dates", admin_letsgo_path %> | <%= link_to "Question & Answers", admin_qanda_path %> | <%= link_to "Pictures", admin_pictures_path %>   
<p>
	
	<div class="row">
	  <div class="col-xs-6">
	    <b>Users By Day<b>
	    <%= line_chart User.group_by_day(:created_at).count %>
		<b>Users By Month<b>
	    <%= line_chart User.group_by_month(:created_at).count %>
		<b>Ethnicity<b>
		<%= pie_chart User.group(:ethnicity).count %>

	  </div>

	</div>
	<p>
	<p>
	<%= User.count %> total users
	<P>
	<%= User.total_males %> Male registered users
	<P>
	<%= User.total_females %> Female registered users
	<P>
	<%= User.group(:ethnicity).count %>
	<p>
		<table class="pretty">
		  <tr>
		    <th>ID</th>
		    <th>User</th>
		    <th>Gender</th>
		    <th>Delete?</th>
		    <th>Subscriber</th>
		    <th>Date</th>
		
		
		  </tr>
		  <%  @users.sort_by(&:created_at).reverse.each do |user| %>
		    <tr>
		      <td><%= user.id %></td>
		      <td><%= link_to user.username, user %></td>
		      <td><%= user.gender %></td>
		      <td><%= link_to "delete", user, method: :delete,
				                                          data: { confirm: "You sure?"} %></td>
		      <td>	<% if user.subscription %> Yes <% end %>
				<% if user.subscription.nil? %> No <% end %></td>
		
		<td><%= user.created_at.strftime("%B %e, %Y") %></td>
		    </tr>
		  <% end %>
		</table>
				<%= will_paginate(@users) %>
				
				<ul>
				  <% @age_groups.each do |age_group| %>
				    <li><%= age_group.from %> - <%= age_group.to %>: <b><%= age_group.count %></b></li>
				  <% end %>
				</ul>