config/routes.rb
require 'sidekiq/web'

Dating::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get 'signup' => 'users#new'
  get 'terms' => 'users#terms_of_use'
  get 'faq' => 'users#faq'
  get 'privacy' => 'users#privacy_policy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  get "/profile/:id" => "users#show"
  get "profile/:id/settings" => 'users#edit'
  get 'settings/:id' => 'users#settings'
  get 'admin/users' => 'admin#users'
  get 'admin/subscriptions' => 'admin#subscriptions'
  get 'admin/letsgo' => 'admin#letsgo'
  get 'admin/messages' => 'admin#messages'
  get 'admin/qanda' => 'admin#qanda'
  get 'admin/pictures' => 'admin#pictures'
  get 'letsgos/eatdrink' => 'letsgos#eatdrink'
  get 'letsgos/listenwatch' => 'letsgos#listenwatch'
  get 'letsgos/play' => 'letsgos#play'
  get 'letsgos/other' => 'letsgos#other'
  get 'letsgos/explore' => 'letsgos#explore'
  get "subscriptions/cancelsubscription"
  get "subscriptions/updatesubscription"
  get "subscriptions/changecard"
  get "subscriptions/suspend"
  get "subscriptions/updatebilling"
  get "subscriptions/reactivate"
  get ":id/updatebilling" => "users#update_stripe_billing"
  match '/edit_card',   to: 'subscriptions#edit_card',   via: 'get'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  get '/relationships/set_follow' => 'relationships#set_follow'
  get '/users/set_follow' => 'users#set_follow'
  get '/speed_dates' => 'users#speed_date'
  get '/disconnect_facebook' => 'users#disconnect_facebook'
  get '/disconnect_twitter' => 'users#disconnect_twitter'

  post 'subscription_event' => "webhooks#subscription_event"
  

    
    resources :messages do
      member do
      post :askout
      end
    end

  resource :twitter do
    get :authorize
    get :return
  end

  get '/auth/facebook', as: "auth_provider"
  get '/auth/facebook/callback', to: 'facebooks#callback'

  match '/paypal/ipn' => 'notifications#create', :via => [:get, :post], :as => 'notifications_create'
  
  resources :admin
  resources :charges
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'paypal/subscription', to: 'subscriptions#paypal_subscription_record', :as => 'paypal_subscription_create'
 
  resources :sessions
  resources :contacts, only: [:new, :create]
  resources :password_resets
  resources :galleries
  resources :photos do
    member do
      post :avatar
    end
  end
  resources :searches do
	get 'save_searches', on: :collection
	get 'load_search', on: :collection
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :letsgos, only: [:create, :destroy]
  resources :users do  
    get 'settings', on: :member  
    post 'follow', on: :member 
    post 'unfollow', on: :member
    get "follow", on: :member 
    get 'follow_popup', on: :member
    post :search, on: :collection
  end
  
  resources :letsgos do
    member do
      post :repost
      post :interested
    end
  end
  
  resources :questions do
    resources :answers, only: [:new, :create]
  end

          
  root to: 'users#index'
  
  resources :users do
  end
 
 resources :conversations do
     post :reply, on: :member
     post :trash_all, on: :collection
     post :untrash, on: :collection
   end

  resources :payments, only: [:show, :create, :destroy] do
     collection do
       get :success
       get :cancel
       post :notify
     end     
   end
   

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def new
    @question = Question.find(params[:question_id])
  end
  
  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end
  
  def create
    @question = Question.find(params[:question_id])
    if @question.update_attributes(params[:question])
      conversation = @question.conversation
      conversation.move_to_trash(current_user)
      post_to_social_network
      flash[:notice] = "Your Answer has been posted to Your Profile."
      redirect_to conversations_path
    else
      render :new
    end
  end

  private

  def post_to_social_network
    access_token = nil
    if params["twitter"]
      begin
        access_token = AccessToken.find_by_user_id_and_social_network(current_user.id, 'T')
        @client = Twitter::REST::Client.new do |config|
            config.consumer_key = "awkQ6gu5lvZuBjAt5yQMCKuVS"
            config.consumer_secret = "CQEwuVlBkA4L17DcXp1jiXLWLGEsFOHV1cX6cUjWDfpqrZhbpV"
            config.access_token = access_token.access_token
            config.access_token_secret = access_token.access_secret
        end
        complete_msg = @question.question+" - "+@question.answer
        @display_message = complete_msg.length <= 110 ? complete_msg : complete_msg[0..39] + '...'
        @con_url = "http://areyoutaken.com"
        @client.update("#{@display_message} #{@con_url}")
      rescue Exception => e
        puts e.message
        puts e.backtrace
        access_token.delete if access_token.present?
      end
    end

    if params["facebook"]
      begin
        access_token = AccessToken.find_by_user_id_and_social_network(current_user.id, 'F')
        api = Koala::Facebook::API.new(access_token.access_token)
        post_details = {
                        :name => @question.question,
                        :picture => "http://ask.fm/images/155x155.png",
                        :link => "http://areyoutaken.com",
                        :description => @question.answer
                       }
        api.put_wall_post("", post_details)
      rescue Exception => e
        puts e.message
        puts e.backtrace
        access_token.delete if access_token.present?
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class = "answers-block">
	<%= simple_format(question.answer) %>
	<p>
		<small><%= answer.user_name %> - <%= time_ago_in_words(answer.created_at) %></small>
		</p>
		</div>

app/views/answers/_form.html.erb
<% if flash[:notice] %>
<p class="flash"><%= flash[:notice] %></p>
<% end %>

<%= form_for(:question, :url => question_answers_path(question)) do |f| %>
	<div class='form_container' style='width: 100%;border: 0 none;'>
		<ul style='list-style: none;'>
			<li><%= f.text_area :answer, {:placeholder => 'Write your answer here...' , :style=>'width:97%;height:50px;resize: none; border: 1px solid #AAA; padding: 10px; margin-bottom: 10px;'} %></li>
			<li><%= hidden_field_tag :recipient_id, {:placeholder => 'Please add your name...' , :style=>'width:97%;border: 1px solid #AAA; padding: 10px; margin-bottom: 10px;'}  %></li>
			<li>
              <%= f.submit "Respond", :class => 'find_btn', :style=>'margin:0' %>
              <div class="social_network">
                <span style="margin-left: -22px;">Twitter</span>
                <%= check_box_tag :twitter, true %>
              </div>
              <div class="social_network">
                <span>Facebook</span>
                <%= check_box_tag :facebook, true %>
              </div>
            </li>
		</ul>
    </div>
<% end %>

<script type="text/javascript">
    window.fbAsyncInit = function() {
        FB.init({
            appId  : '493696170783447',
            status : true,
            cookie : true, 
            xfbml  : true 
        });
    };

    (function(d) {
        var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/en_US/all.js";
        d.getElementsByTagName('head')[0].appendChild(js);
    }(document));

    $(function() {
        if(<%= current_user_has_fb_access_token? %> == false)
        {
            $("#facebook").click(function (e) {
                if (this.checked) {
                    FB.login(function(response) {
                        if (response.authResponse) {                           
                            $.getJSON('/auth/facebook/callback', function(json) {
                                e.stopPropagation();
                                return true;
                            });
                        }
                    }, { scope: 'user_about_me, publish_actions, manage_pages' }); // These are the permissions you are requesting
                }
            });
        }

    });


  if(<%= current_user_has_tw_access_token? %> == false){
      $("#twitter").click(function(e) {
          if(this.checked) {
              var left = (screen.width/2)-(400/2);
              var top = (screen.height/2)-(400/2);
              window.open('<%= authorize_twitter_url(:target_profile_id => current_user.id) %>', "", 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+400+', height='+400+', top='+top+', left='+left);
              e.stopPropagation();
              return true;
          }
      });
  }
</script>

app/views/answers/_show.html.erb
	<%= @question%>