config/routes.rb
require 'sidekiq/web'

Dating::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get 'signup' => 'users#new'
  get 'terms' => 'users#terms_of_use'
  get 'faq' => 'users#faq'
  get 'privacy' => 'users#privacy_policy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  get "/profile/:id" => "users#show"
  get "profile/:id/settings" => 'users#edit'
  get 'settings/:id' => 'users#settings'
  get 'admin/users' => 'admin#users'
  get 'admin/subscriptions' => 'admin#subscriptions'
  get 'admin/letsgo' => 'admin#letsgo'
  get 'admin/messages' => 'admin#messages'
  get 'admin/qanda' => 'admin#qanda'
  get 'admin/pictures' => 'admin#pictures'
  get 'letsgos/eatdrink' => 'letsgos#eatdrink'
  get 'letsgos/listenwatch' => 'letsgos#listenwatch'
  get 'letsgos/play' => 'letsgos#play'
  get 'letsgos/other' => 'letsgos#other'
  get 'letsgos/explore' => 'letsgos#explore'
  get "subscriptions/cancelsubscription"
  get "subscriptions/updatesubscription"
  get "subscriptions/changecard"
  get "subscriptions/suspend"
  get "subscriptions/updatebilling"
  get "subscriptions/reactivate"
  get ":id/updatebilling" => "users#update_stripe_billing"
  match '/edit_card',   to: 'subscriptions#edit_card',   via: 'get'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  get '/relationships/set_follow' => 'relationships#set_follow'
  get '/users/set_follow' => 'users#set_follow'
  get '/speed_dates' => 'users#speed_date'
  get '/disconnect_facebook' => 'users#disconnect_facebook'
  get '/disconnect_twitter' => 'users#disconnect_twitter'

  post 'subscription_event' => "webhooks#subscription_event"
  

    
    resources :messages do
      member do
      post :askout
      end
    end

  resource :twitter do
    get :authorize
    get :return
  end

  get '/auth/facebook', as: "auth_provider"
  get '/auth/facebook/callback', to: 'facebooks#callback'

  match '/paypal/ipn' => 'notifications#create', :via => [:get, :post], :as => 'notifications_create'
  
  resources :admin
  resources :charges
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'paypal/subscription', to: 'subscriptions#paypal_subscription_record', :as => 'paypal_subscription_create'
 
  resources :sessions
  resources :contacts, only: [:new, :create]
  resources :password_resets
  resources :galleries
  resources :photos do
    member do
      post :avatar
    end
  end
  resources :searches do
	get 'save_searches', on: :collection
	get 'load_search', on: :collection
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :letsgos, only: [:create, :destroy]
  resources :users do  
    get 'settings', on: :member  
    post 'follow', on: :member 
    post 'unfollow', on: :member
    get "follow", on: :member 
    get 'follow_popup', on: :member
    post :search, on: :collection
  end
  
  resources :letsgos do
    member do
      post :repost
      post :interested
    end
  end
  
  resources :questions do
    resources :answers, only: [:new, :create]
  end

          
  root to: 'users#index'
  
  resources :users do
  end
 
 resources :conversations do
     post :reply, on: :member
     post :trash_all, on: :collection
     post :untrash, on: :collection
   end

  resources :payments, only: [:show, :create, :destroy] do
     collection do
       get :success
       get :cancel
       post :notify
     end     
   end
   

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan
  belongs_to :subscription
  belongs_to :user
  
  validates_presence_of :plan_id
  validates_presence_of :email
  
  attr_accessor :stripe_card_token, :paypal_payment_token
  
  def self.total_male
    count_of_males = Subscription.joins(:user).where(users: {gender: 'male'}).uniq.count
  end
  
  def self.total_female
    count_of_males = Subscription.joins(:user).where(users: {gender: 'female'}).uniq.count
  end
  
  def self.total_annual
      where('plan_id = 12').count
    end
    
    def self.total_monthly
        where('plan_id = 1').count
      end
  
  def self.total_paypal_recurring_profile_token
      where('paypal_recurring_profile_token IS NOT NULL').count
    end
    
    def self.total_stripe_customer_token
        where('stripe_customer_token IS NOT NULL').count
      end
      
      def self.total_stripe_cancelled
          where('stripe_customer_token IS NOT NULL and cancelled IS NOT NULL').count
        end
        
        def self.total_paypal_cancelled
            where('paypal_recurring_profile_token IS NOT NULL and cancelled IS NOT NULL').count
          end
  
      def self.total_cancelled
          where('cancelled IS NOT NULL').count
        end
  
        def self.total_active
            where('cancelled IS NULL').count
          end
          
            def self.total_active_stripe
                where('stripe_customer_token IS NOT NULL and cancelled IS NULL').count
              end
              
              def self.total_active_paypal
                  where('paypal_recurring_profile_token IS NOT NULL and cancelled IS NULL').count
                end
          
  def has_cancelled?
    if cancellation_date.present? && cancellation_date > (paid_on + 30)
      subscription.update_attributes(cancelled: "1")
      return true
    else
      return false
    end
  end
  
  def expires_at
    self.updated_at + plan.duration.days
  end
  
  def save_with_payment
    if valid?
      if paypal_payment_token.present?
        save_with_paypal_payment
      else
        save_with_stripe_payment
      end
    end
  end
  
  def paypal
    PaypalPayment.new(self)
  end
  
  def save_with_paypal_payment
    response = paypal.make_recurring
    self.paypal_recurring_profile_token = response.profile_id
    save!
  end

  def save_with_stripe_payment
    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    self.stripe_customer_token = customer.id
    self.cancellation_date = Time.zone.at(customer.subscriptions.first.current_period_end)
    save!
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
  
  def payment_provided?
    stripe_card_token.present? || paypal_payment_token.present?
  end
  
  def suspend_paypal
    paypal.suspend
    save
  end
  
  
  def reactivate_paypal
    paypal.reactivate
    save
  end
  
  def update_card(subscriber, card_info)
  token = Stripe::Token.create(
    card: {
      number: card_info[:number],
      exp_month: card_info[:exp_month],
      exp_year: card_info[:exp_year],
      cvc: card_info[:cvc]
    }
  )
  customer = Stripe::Customer.retrieve(user.subscription.stripe_customer_token)
  card = customer.cards.create(card: token.id)
  card.save
  customer.default_card = card.id
  customer.save
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while updating card info: #{e.message}"
    errors.add :base, "#{e.message}"
    false
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  
  def new
    plan_id = params[:plan_id] || 12
    plan = Plan.find(plan_id)
    @subscription = plan.subscriptions.build
    if params[:PayerID]
      @subscription.paypal_customer_token = params[:PayerID]
      @subscription.paypal_payment_token = params[:token]
      @subscription.email = @subscription.paypal.checkout_details.email
    end
    render layout: 'new_application'
    
  end

  def create
    @user = current_user
    @subscription = Subscription.new(params[:subscription])
    if @subscription.save_with_payment
      UserMailer.subscriber(@user).deliver
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end
  
  def paypal_subscription_record
	@user = current_user
	plan_id = params[:plan_id] || 1
	subscription = {"plan_id"=>plan_id, 
					 "stripe_card_token"=>"", 
					 "paypal_customer_token"=>params[:PayerID], 
					 "paypal_payment_token"=>params[:token], 
					 "user_id"=>@user.id, 
					 "email"=>@user.email}
    @subscription = Subscription.new(subscription)
    if @subscription.save_with_payment
      UserMailer.subscriber(@user).deliver
      redirect_to @subscription, :notice => "Thank you for subscribing!"
    else
      render :new
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
    render layout: 'new_application'
  end
  
  def paypal_checkout
    plan = Plan.find(params[:plan_id])
    subscription = plan.subscriptions.build
    redirect_to subscription.paypal.checkout_url(
      return_url: paypal_subscription_create_url(:plan_id => plan.id),
      cancel_url: root_url
    )
  end
    
    def updatesubscription
      @user = current_user
      @customer = Stripe::Customer.retrieve(@user.subscription.stripe_customer_token)
      if @user.subscription.plan_id == 12
      @customer.update_subscription(:plan => "1", :prorate => true)
      current_user.subscription.update_attributes(:plan_id => 1)
      flash.alert = 'Your subscription has been changed to monthly!'
      redirect_to root_url
    elsif @user.subscription.plan_id == 1
      @customer.update_subscription(:plan => "12", :prorate => true)
      current_user.subscription.update_attributes(:plan_id => 12)
     current_user.save!
      flash.alert = 'Your subscription has been changed to annually!'
      redirect_to root_url
    end
     end

     def cancelsubscription
       @user = current_user
         @customer = Stripe::Customer.retrieve(@user.subscription.stripe_customer_token)
         @customer.cancel_subscription(:at_period_end => true) 
         current_user.save!
         flash.alert = 'Your subscription has been cancelled successfully!'
         redirect_to root_url
       end
       
       def showcard
         @user = current_user
         Stripe::Customer.retrieve(@user.subscription.stripe_customer_token).cards.all()
       end
           
           def suspend
             @user = current_user
             @user.subscription.suspend_paypal
             current_user.subscription.update_attributes(:cancelled => 1)
               flash.alert = 'Subscription has been cancelled!'
                redirect_to root_url
           end

           def reactivate
             @user = current_user
             @user.subscription.reactivate_paypal
             current_user.subscription.update_attributes(:cancelled => nil)
               flash.alert = 'Subscription has been activated!'
                redirect_to root_url
           end
         
     
               def edit_card
                 @user = current_user
               end

               def update_card
                 @user = current_user
                 card_info = {
                   name:    params[:name],
                   number:    params[:number],
                   exp_month: params[:date][:month],
                   exp_year:  params[:date][:year],
                   cvc:       params[:cvc]
                 }
                 if @user.subscription.update_card(@subscriber, card_info)
                   flash.alert = 'Saved. Your credit card information has been updated.'
                   redirect_to root_url
                 else
                   flash.alert = 'Stripe reported an error while updating your card. Please try again.'
                   redirect_to root_url
                 end
               end
end

app/views/subscriptions/_plans.html.slim
- sender = conversation.last_sender
- message = conversation.last_message
- receipts = conversation.receipts.recipient(@user).is_unread
- is_unread = receipts.count > 0 ? true : false
.outer
  div.converation class="#{is_unread == true ? 'unread' : 'read'}" onclick="#" data-href="#{conversation_path(conversation)}"
    .col_1
      img alt="" src="#{is_unread == true ? '/assets/un_read.png' : '/assets/read.png'}" /
      span.conversation_avatar
        =link_to "/profile/#{sender.id}" do
          img alt="" src="#{sender.avatar.image_url(:avatar)}" /
      h5 = sender.username
      strong 
        = sender.age
        ', 
        = sender.gender
        ',
        = sender.sexuality
      small
        br
        = sender.location.city
        ',
        = sender.location.state
    .col_2
      span = message.subject
      p = message.body
    .col_3
      strong = extract_date(message.created_at)
      small = extract_time(message.created_at)
  form action="#" 
    fieldset
      input type="checkbox" class="conversation_checkbox"

app/views/subscriptions/changecard.html.erb
Add new Credit Card
<%= form_for @user do |f| %>
  <% if @subscription.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :plan_id %>
  <%= f.hidden_field :stripe_card_token %>

  <div class="field">
    <%= radio_button_tag :pay_with, :card, true %>
    <%= label_tag :pay_with_card do %>
      <%= image_tag "visa.png" %>
      <%= image_tag "mastercard.png" %>
      <%= image_tag "discover.png" %>
      <%= image_tag "american_express.png" %>
      <%= image_tag "jcb.png" %>
  </div>
  <% end %>

  <div id="billing_fields">
    <div class="field">
	  <%= f.hidden_field :user_id, :value => current_user.id %> 
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <% if @subscription.payment_provided? %>
      Payment has been provided. Click "Subscribe" to complete the subscription.
    <% else %>
      <div class="field">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_code, "Security Code on Card (CVV)" %>
        <%= text_field_tag :card_code, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_month, "Card Expiration" %>
        <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
      </div>
    <% end %>
    <div id="stripe_error">
      <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
    </div>
    <div class="actions">
      <%= f.submit "New Card" %>
    </div>
  </div>
<% end %>

app/views/subscriptions/edit_card.html.erb
<%= form_tag( { controller: 'subscriptions', action: 'update_card' }, method: 'post', class: 'form-horizontal') do %>
  <div class='form-group'>
    <%= label_tag        :number, 'Card Number', class: 'col-sm-3 control-label' %>
    <div class='col-sm-9'>  
      <%= text_field_tag :number, nil, class: 'form-control', placeholder: 'We accept Visa, MasterCard, AMEX and Discover' %>
    </div>
  </div>

  <div class='form-group'>
    <%= label_tag        :cvc, 'Security Code', class: 'col-sm-3 control-label' %>
      <div class='col-sm-9'>
        <%= text_field_tag :cvc, nil, class: 'form-control', placeholder: 'The code on the back of your card (CVC)' %>
      </div>
  </div>

  <div class='form-group'>
    <%= label_tag        :exp_month, 'Expiration Date', class: 'col-sm-3 control-label' %>
    <div class='col-sm-5'>
      <%= select_month   nil, { add_month_numbers: true }, { id: 'exp_month', class: 'form-control btm-space' } %>
    </div>
    <div class='col-sm-4'>
      <%= select_year    nil, { start_year: Date.today.year, end_year: Date.today.year+15 }, { id: 'exp_year', class: 'form-control btm-space' } %>
    </div>
  </div>
  <div class='form-group'>
    <div class='col-sm-4 col-sm-offset-8'>
      <%= submit_tag 'Update', class: 'btn btn-success btn-block' %>
    </div>
  </div>
<% end %>

app/views/subscriptions/new.html.erb
<div class="col-9">
 <%= form_for @subscription do |f| %>
  <div class="col-3">
    <div class="plan">

      <h1><%= radio_button_tag "subscription[plan_id]", '1', (@subscription.plan.id == 1 ? true : false) %><label for="plan_id_1"><span><span></span></span></label>$1.35 a month</h1>
      <h2>1-Month Membership</h2>
      <li><p>View all locals in your area</p>
	  <li><p>Play Speed Date</p>
	  <li><p>Receive and read unlimited messages</p>
    </div>
    <div class="plan">
      <h1><%= radio_button_tag "subscription[plan_id]", '12', (@subscription.plan.id == 12 ? true : false) %><label for="plan_id_12"><span><span></span></span></label>$13.50 a month</h1>
      <h2>12-Month Membership</h2>
      <li><p>2 FREE months!</p>
      <li><p>Send unlimited messages to any user</p>
	  <li><p>Receive and read unlimited messages</p>
	  <li><p>Book the dates you like</p>
    </div>
  </div>
  <div class="sm_form_container">
    <div class="row">
      <div class="field">
        <h1>Signing up for "<%= @subscription.plan.name %>"</h1>
        <p>Includes <strong><%= @subscription.plan.length %> days</strong> for only <strong><%= number_to_currency @subscription.plan.price %></strong>!</p>
     </div>
    </div> 
    <div class="row">
      <div class="field">
    
      <% if @subscription.errors.any? %>
        
          <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
          <ul>
          <% @subscription.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        
      <% end %>
    
      <%= f.hidden_field :stripe_card_token %>
      <%= f.hidden_field :paypal_customer_token %>
      <%= f.hidden_field :paypal_payment_token %>
    
      <% unless @subscription.payment_provided? %>
      
        <%= radio_button_tag :pay_with, :card, true %>
        <%= label_tag :pay_with_card do %>
          <%= image_tag "visa.png" %>
          <%= image_tag "mastercard.png" %>
          <%= image_tag "discover.png" %>
          <%= image_tag "american_express.png" %>
          <%= image_tag "jcb.png" %>
        <% end %>
        <%= radio_button_tag :pay_with, :paypal %>
        <%= label_tag :pay_with_paypal do %>
          <%= image_tag "paypal.png" %>
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="row">
      <div id="paypal_checkout" style="display:none">
	   <%= link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(plan_id: @subscription.plan_id) %>
	
      </div>
    </div>
    <div id="billing_fields">
      <div class="field">
    	  <%= f.hidden_field :user_id, :value => current_user.id %> 
          <%= f.hidden_field :email, :value => current_user.email  %>
        </div>
        <% if @subscription.payment_provided? %>
          Payment has been provided. Click "Subscribe" to complete the subscription.
        <% else %>
      <div class="row">
          <div class="field">
            <%= label_tag :card_owner, "Name (as it appears on the card)" %>
            <%= text_field_tag :card_owner, nil, name: nil %>
          </div>
          <div class="field">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, name: nil %>
          </div>
      </div>
      <div class="row">
          <div class="field">
            <%= label_tag :card_code, "Security Code on Card (CVV)" %>
            <%= text_field_tag :card_code, nil, name: nil %>
          </div>
          <div class="field" id="expiration">
            <%= label_tag :card_month, "Card Expiration" %><br />
            <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
            <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
          </div>
        <% end %>
        <div id="stripe_error">
          <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
        </div>
      </div>
      <div class="row">
        <div class="field"><%= f.submit "Subscribe", class: 'btn', style: "width: 40%; margin-left: 165px"  %></div>
      </div>
      </div>
    <% end %>
  </div>
</div>
<script>
  $("input[name='subscription[plan_id]']").on('change', function(){
      window.location.assign("<%= new_subscription_url %>?plan_id="+$(this).val());
  });

</script>

app/views/subscriptions/show.html.erb
<div id="subscription">
  <h1>Your Subscription Details</h1>
  <p>Congratulations! You have signed up for the <strong><%= @subscription.plan.name %></strong> plan which includes <strong><%= @subscription.plan.length %>  days</strong> for just <strong><%= number_to_currency @subscription.plan.price %></strong> per month!<p>
  	
You're now one step closer to getting offline and finding your match. You should begin by creating a Date and then take a stroll over to the "Find Dates" section. From there you can find dates that interest you.<P>
	
If you need any assistance with our service, from technical issues to advice, you can contact us.<P>
	
Thank you for joining AreYouTaken!
  </p>
</div>

<p>
	