config/routes.rb
require 'sidekiq/web'

Dating::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'

  get 'signup' => 'users#new'
  get 'terms' => 'users#terms_of_use'
  get 'faq' => 'users#faq'
  get 'privacy' => 'users#privacy_policy'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'edit' => 'users#edit'
  get "/profile/:id" => "users#show"
  get "profile/:id/settings" => 'users#edit'
  get 'settings/:id' => 'users#settings'
  get 'admin/users' => 'admin#users'
  get 'admin/subscriptions' => 'admin#subscriptions'
  get 'admin/letsgo' => 'admin#letsgo'
  get 'admin/messages' => 'admin#messages'
  get 'admin/qanda' => 'admin#qanda'
  get 'admin/pictures' => 'admin#pictures'
  get 'letsgos/eatdrink' => 'letsgos#eatdrink'
  get 'letsgos/listenwatch' => 'letsgos#listenwatch'
  get 'letsgos/play' => 'letsgos#play'
  get 'letsgos/other' => 'letsgos#other'
  get 'letsgos/explore' => 'letsgos#explore'
  get "subscriptions/cancelsubscription"
  get "subscriptions/updatesubscription"
  get "subscriptions/changecard"
  get "subscriptions/suspend"
  get "subscriptions/updatebilling"
  get "subscriptions/reactivate"
  get ":id/updatebilling" => "users#update_stripe_billing"
  match '/edit_card',   to: 'subscriptions#edit_card',   via: 'get'
  match '/update_card', to: 'subscriptions#update_card', via: 'post'
  get '/relationships/set_follow' => 'relationships#set_follow'
  get '/users/set_follow' => 'users#set_follow'
  get '/speed_dates' => 'users#speed_date'
  get '/disconnect_facebook' => 'users#disconnect_facebook'
  get '/disconnect_twitter' => 'users#disconnect_twitter'

  post 'subscription_event' => "webhooks#subscription_event"
  

    
    resources :messages do
      member do
      post :askout
      end
    end

  resource :twitter do
    get :authorize
    get :return
  end

  get '/auth/facebook', as: "auth_provider"
  get '/auth/facebook/callback', to: 'facebooks#callback'

  match '/paypal/ipn' => 'notifications#create', :via => [:get, :post], :as => 'notifications_create'
  
  resources :admin
  resources :charges
  resources :subscriptions
  resources :plans
  get 'paypal/checkout', to: 'subscriptions#paypal_checkout'
  get 'paypal/subscription', to: 'subscriptions#paypal_subscription_record', :as => 'paypal_subscription_create'
 
  resources :sessions
  resources :contacts, only: [:new, :create]
  resources :password_resets
  resources :galleries
  resources :photos do
    member do
      post :avatar
    end
  end
  resources :searches do
	get 'save_searches', on: :collection
	get 'load_search', on: :collection
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :letsgos, only: [:create, :destroy]
  resources :users do  
    get 'settings', on: :member  
    post 'follow', on: :member 
    post 'unfollow', on: :member
    get "follow", on: :member 
    get 'follow_popup', on: :member
    post :search, on: :collection
  end
  
  resources :letsgos do
    member do
      post :repost
      post :interested
    end
  end
  
  resources :questions do
    resources :answers, only: [:new, :create]
  end

          
  root to: 'users#index'
  
  resources :users do
  end
 
 resources :conversations do
     post :reply, on: :member
     post :trash_all, on: :collection
     post :untrash, on: :collection
   end

  resources :payments, only: [:show, :create, :destroy] do
     collection do
       get :success
       get :cancel
       post :notify
     end     
   end
   

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :subscriptions
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.order("price")
  end
end

app/views/plans/_form.html.erb
<%= form_for @plan do |f| %>
  <h2>
  </h2>
  <%= f.text_field :unit_name, placeholder: 'Name for metered usage unit' %>
  <%= f.text_field :included_units, placeholder: 'Included metered usage units' %>
  <%= f.text_field :overage_price, placeholder: 'Price per additional unit (cents)' %>
  <%= f.text_field :unavailable, hint: 'Will remove from user facing list' %>
  <%= f.text_field :description, placeholder: 'HAML will be interpreted' %>
  <div class="form-actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/plans/index.html.erb
<div id="plans">
  <h1>Dating Subscription</h1>
  <% @plans.each do |plan| %>
    <div class="plan">
      <div class="name"><%= plan.name %></div>
      <div class="details">
        <div class="price">
          <%= number_to_currency plan.price, :precision => 0 %>
        </div>
        <div class="per_month">per month</div>
        <div class="kisses"><%= plan.length %> length</div>
        <div class="per_month">per month</div>
        <div class="signup">
          <%= link_to "Sign up", new_subscription_path(:plan_id => plan.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>